/* Amplify Params - DO NOT EDIT
	API_SERVERLESSPLAYGROUND_GRAPHQLAPIENDPOINTOUTPUT
	API_SERVERLESSPLAYGROUND_GRAPHQLAPIIDOUTPUT
	API_SERVERLESSPLAYGROUND_GRAPHQLAPIKEYOUTPUT
	ENV
	REGION
Amplify Params - DO NOT EDIT */

exports.handler = async (message: string) => {
  console.log('MESSAGE', message);

  return 'Hello world';
};
